defaults:
  - _self_
  - agent: default_actor_critic
  - optimizer: adamw

device: cuda:1

logging:
  project_name: snake_reinforced
  run_name: pg_baseline_00
  log_video_every_n_epoch: 50
  video_filename: ./videos/${logging.run_name}/snake__epoch_{epoch_i}.mp4
  n_last_frames: 1000


training:
  gamma_discount: 0.99
  
  lr: 1e-3
  weight_decay: 1e-5
  
  batch_size: 32

loss:
  value_weight: 0.5
  entropy_weight: -0.001
